name: finova-statement
services:
  mongo:
    build: ./db
    environment:
      - DB_NAME=${DB_NAME:-finovabank}
      - DB_USER=${DB_USER:-finova}
      - DB_PASS=${DB_PASS:-bb4981aa2048c4e9e791ab6fe67e7e72}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 40
    networks:
      - app-network
    restart: always

  app:
    build:
      context: ./app
      args:
        - FLAG=${FLAG:-DF25{Y0u_c0UlD_5p3L_7h3_3xpr35510N!!}}
    security_opt:
      - no-new-privileges:true
    ports:
      - 127.0.0.1:11337:8080 # 1337
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/${DB_NAME:-finovabank}
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "127.1:8080"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
