name: gadgets-store
services:
  challenge:
    build:
      context: ./gadgets-store
      dockerfile: Dockerfile.prod
    ports:
      - 127.0.0.1:13337:8080 # 1337
    environment:
      - DATASOURCE_NAME=${POSTGRES_DB:-gadgets_store}
      - DATASOURCE_HOST=${DATASOURCE_HOST:-db}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME:-admin}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD:-9def3b1c8a63051a5cdf91ed1b35edfa}
    networks:
      - internal

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        - FLAG=${FLAG:-DFCD{e9cbbab914766ce8c311772dce7c28b1}}
    environment:
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME:-admin}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD:-9def3b1c8a63051a5cdf91ed1b35edfa}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-cfaef0ac71d5a033d200dd7295114d9f}
      - POSTGRES_DB=${POSTGRES_DB:-gadgets_store}
    user: postgres:postgres
    networks:
      - internal

networks:
  internal:
    driver: bridge
